[build]
  base = "Client"
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"

[context.production.environment]
  VITE_API_URL = "https://earthlens-3.onrender.com/api"
